### ISSUE TITLE
Problem at setting up the starter with different database credentials

### ISSUE THREAD

**Issue by abusarah-tech** [medusajs/b2b-starter-medusa#75]
### Describe the bug

Trying to set up the b2b starter with an existing database instance that has different credentials (username, password) but it throws an error. (see the screenshot below)

### System information

Node.js version: v22.8.0
Database: Postgres 14 
Operating system: WSL (Ubuntu 22.04)

### Steps to reproduce the behavior

1. Create database instance using docker compose with the following setup 
```
services:
  medusa-db:
    image: postgres:14
    environment:
      - POSTGRES_DB=medusa-backend
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  medusa-cache:
    image: redis:6
    ports:
      - "6379:6379"
```
2. Clone the repository and run `yarn install && yarn setup`

### Expected behavior

It should to prompt me to enter the database credentials then the database name then complete the setup.

### Screenshots

![image](https://github.com/user-attachments/assets/1f800872-ba74-46e3-815f-9268a441ea8e)
